
import { jsPDF } from 'jspdf';
import { ODRequest } from '../types';

export const generateODLetter = async (request: ODRequest): Promise<Blob> => {
  const doc = new jsPDF();
  const date = new Date().toLocaleDateString();

  // Header
  doc.setFontSize(16);
  doc.setTextColor(20, 60, 110);
  doc.text('CIVLOG CIVIL ENGINEERING DEPARTMENT', 105, 20, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text('OFFICIAL ON-DUTY (OD) PERMISSION LETTER', 105, 30, { align: 'center' });
  
  doc.line(20, 35, 190, 35);

  // Date and To
  doc.setFontSize(11);
  doc.text(`Date: ${date}`, 20, 45);
  doc.text('To,', 20, 55);
  doc.text('The Head of Department,', 20, 60);
  doc.text('Department of Civil Engineering.', 20, 65);

  // Body
  doc.text('Subject: Requisition for On-Duty (OD) Permission - Regarding.', 20, 80);
  
  let bodyText = `This is to certify that ${request.student_name} (Reg No: ${request.register_no}, Roll No: ${request.roll_no}, Phone: ${request.phone_number}) of ${request.year} Year / ${request.semester} Semester has been granted On-Duty permission to participate in the event "${request.event_title}" organized by ${request.organization_name}${request.organization_location ? ', ' + request.organization_location : ''}.`;
  
  const splitText = doc.splitTextToSize(bodyText, 170);
  doc.text(splitText, 20, 95);

  // Team Members Section
  if (request.team_members && request.team_members.length > 0) {
    let yPos = 120;
    doc.setFont(undefined, 'bold');
    doc.text('Additional Team Members:', 20, yPos);
    doc.setFont(undefined, 'normal');
    request.team_members.forEach((member, index) => {
      yPos += 7;
      doc.text(`${index + 1}. ${member.name} - ${member.year} Year (Reg: ${member.register_no}, Roll: ${member.roll_no})`, 25, yPos);
    });
  }

  const footY = Math.max(170, (request.team_members?.length || 0) * 7 + 130);
  doc.text(`Event Date: ${request.event_date}`, 20, footY);
  doc.text(`Event Type: ${request.event_type}`, 20, footY + 5);

  doc.text('The student is expected to submit participation evidence (Geotagged Photo & Certificate) immediately after the event to complete the OD cycle.', 20, footY + 20, { maxWidth: 170 });

  // Signature
  doc.text('Sd/-', 150, footY + 50);
  doc.text('Faculty In-Charge', 150, footY + 55);
  doc.text('Civil Engineering', 150, footY + 60);

  // Footer
  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  doc.text('This is an automated document generated by the CivLog OD-Track System.', 105, 285, { align: 'center' });

  return doc.output('blob');
};
